// DO NOT EDIT! Auto-generated by LayoutFilesGenerator.php

import * as $ from "jquery";
import {Layout} from "../src/ts/layouts/Layout";
import {Article} from "./layouts/article/Article";
import {TopNav} from "./layouts/topnav/TopNav";
import {linkcard} from "./layouts/linkcard/linkcard";
import {HeroMedia} from "./layouts/heromedia/HeroMedia";
import {HeroResultDisplay} from "./layouts/heroresultdisplay/HeroResultDisplay";
import {foxgallary} from "./layouts/foxgallary/foxgallary";
import {BookDisplay} from "./layouts/bookdisplay/BookDisplay";
import {ImageDisplay} from "./layouts/imagedisplay/ImageDisplay";
import {HeroMediaQuiz} from "./layouts/heromediaquiz/HeroMediaQuiz";
import {Hero} from "./layouts/hero/Hero";
import {IconLinklist} from "./layouts/icon_linklist/IconLinklist";
import {Linklist} from "./layouts/linklist/Linklist";
import {Map} from "./layouts/map/Map";
import {Somenav} from "./layouts/some_navigation/Somenav";
import {Timeline} from "./layouts/timeline/Timeline";
import {TimelineTextual} from "./layouts/timeline_textual/TimelineTextual";


export class Layouts {
	private layouts:Array<Layout>;
	
	constructor() {
		let self = this;
		this.layouts = [];
		
        $(".article").each(function (index, element) {
            self.layouts.push( new Article($(element)) );
        });

        $(".topnav").each(function (index, element) {
            self.layouts.push( new TopNav($(element)) );
        });

        $(".linkcard").each(function (index, element) {
            self.layouts.push( new linkcard($(element)) );
        });

        $(".heromedia").each(function (index, element) {
            self.layouts.push( new HeroMedia($(element)) );
        });

        $(".heroresultdisplay").each(function (index, element) {
            self.layouts.push( new HeroResultDisplay($(element)) );
        });

        $(".foxgallary").each(function (index, element) {
            self.layouts.push( new foxgallary($(element)) );
        });

        $(".bookdisplay").each(function (index, element) {
            self.layouts.push( new BookDisplay($(element)) );
        });

        $(".imagedisplay").each(function (index, element) {
            self.layouts.push( new ImageDisplay($(element)) );
        });

        $(".heromediaquiz").each(function (index, element) {
            self.layouts.push( new HeroMediaQuiz($(element)) );
        });

        $(".hero").each(function (index, element) {
            self.layouts.push( new Hero($(element)) );
        });

        $(".icon-linklist").each(function (index, element) {
            self.layouts.push( new IconLinklist($(element)) );
        });

        $(".linklist").each(function (index, element) {
            self.layouts.push( new Linklist($(element)) );
        });

        $(".map").each(function (index, element) {
            self.layouts.push( new Map($(element)) );
        });

        $(".some-navigation").each(function (index, element) {
            self.layouts.push( new Somenav($(element)) );
        });

        $(".timeline").each(function (index, element) {
            self.layouts.push( new Timeline($(element)) );
        });

        $(".timeline-textual").each(function (index, element) {
            self.layouts.push( new TimelineTextual($(element)) );
        });

;
	}

	public getLayouts( className:string ):Layout[]{
		return this.layouts.filter( layout => layout.name() == className );
	}
		
	public getLayout( className:string ):Layout{
		return this.layouts.filter( layout => layout.name() == className )[0];
	}
}